project:
  type: website

website:
  title: "life_in_a_jar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - wally.qmd
      - Ziggy.qmd
      

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true



